version: 1.0.{build}
image: Visual Studio 2015
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - ps: nuget restore .\SalaryCalculator\SalaryCalculator.sln
build:
  project: .\SalaryCalculator\SalaryCalculator.sln
  verbosity: minimal
notifications:
  - provider: Email
    to:
    - nestorov.alexander@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: ghd3wcmMDkCGJiiDs0vyaQEyr1fk9VzTmxbfUT6ykaBCTJ5UJSre9UoMZ36kMd6P
after_test:
  - SalaryCalculator\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"SalaryCalculator\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single  SalaryCalculator\SalaryCalculatorWeb.Tests\bin\Release\SalaryCalculatorWeb.Tests.dll" -output:coverage.xml
  - SalaryCalculator\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml --full-sources
